name: Derrick Kwa
favicon: null
layout_spectrum: 0.6660760836675763
typography_spectrum: 0.25339320045895875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7590014303568751
  lightness: 0.6130086933262646
  saturation: 0.7176529527641833
  rhythmicContrast: 0.42279988853260875
purpose: []
